version: "3.5"
networks:
  be:
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: user1
      MARIADB_DATABASE: db1
      MARIADB_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    networks:
      - be
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - be
